packages:
  - packages/*

catalog:
  '@antfu/eslint-config': 5.4.1
  '@cloudflare/vitest-pool-workers': 0.9.8
  '@nuxt/eslint': 1.9.0
  '@nuxt/image': 1.11.0
  '@nuxt/test-utils': 3.19.2
  '@nuxt/ui': 4.0.0
  '@nuxtjs/supabase': ^2.0.0
  '@pinia/nuxt': 0.11.2
  '@prettier/plugin-xml': 3.4.2
  '@rivetkit/cloudflare-workers': 2.0.6
  '@scryfall/api-types': 1.0.0-alpha.4
  '@supabase/supabase-js': 2.58.0
  '@types/node': 24.6.1
  '@vue/test-utils': 2.4.6
  '@vueuse/core': 13.9.0
  '@vueuse/nuxt': 13.9.0
  defu: 6.1.4
  drizzle-kit: 0.31.5
  drizzle-orm: 0.44.5
  eslint: 9.36.0
  eslint-plugin-drizzle: 0.2.3
  eslint-plugin-format: 1.0.2
  happy-dom: 18.0.1
  nanoid: 5.1.6
  nuxt: 4.1.2
  pinia: 3.0.3
  playwright-core: 1.55.1
  postgres: 3.4.7
  rivetkit: 2.0.6
  socket.io: 4.8.1
  socket.io-client: 4.8.1
  tailwindcss: 4.1.13
  typescript: 5.9.3
  vitest: 3.2.4
  vue: 3.5.22
  vue-router: 4.5.1
  vue-tsc: 3.1.0
  wrangler: 4.40.3
  zod: 4.1.11

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - cbor-extract
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd
